export const FETCH_ORIGIN_DATA = 'FETCH_ORIGIN_DATA';
export const FETCH_DESTINATION_DATA = 'FETCH_DESTINATION_DATA';
export const FETCH_EXCHANGE_RATE_DATA = 'FETCH_EXCHANGE_RATE_DATA';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';
export const FETCH_DATA_ERROR_RESET = 'FETCH_DATA_ERROR_RESET';
export const SELECTED_DESTINATION = 'SELECTED_DESTINATION';